### ISSUE TITLE
Write first basic TUI

### ISSUE THREAD

**Issue by drescherflo** [drescherflo/de.htwg.se.Wizard#13]
For example, one could ask the user to input the players names and print them out.
Later we can also print out the cards that got assigned to each player.

**Comment by vanessa510** [comment]
define the initial state of the game.

**Comment by drescherflo** [comment]
This is actually a good idea. One could begin with reading in the number of players (3-6) and map the input to the number of rounds to be played.

**Comment by vanessa510** [comment]
Asked players for number of players and printed them. Asked them for their names and printed them as well. Exit program with 'q'.
