### ISSUE TITLE
Test for DefaultCard

### ISSUE THREAD

**Issue by drescherflo** [drescherflo/de.htwg.se.Wizard#3]
1. Implement missing tests for current functionality.
2. Don't allow to create a DefaultCard with other colours than green, yellow, blue or red.
3. Allow to create a DefaultCard only if number is in range from 1 to 13.

**Comment by vanessa510** [comment]
Finished first task

**Comment by drescherflo** [comment]
Implemented task 3.

**Comment by drescherflo** [comment]
Implemented task 3.

**Comment by vanessa510** [comment]
Finished task 2.
