### ISSUE TITLE
Compare two cards with each other

### ISSUE THREAD

**Issue by vanessa510** [drescherflo/de.htwg.se.Wizard#8]
Comparing the numbers of two cards.

**Comment by drescherflo** [comment]
This doesn't seem to work, as scala does not seem to allow DefaultCard > JesterCard or other comparing methods between different classes, even if they extend the same trait and the trait extends Ordered.
Maybe we can fix this in a few weaks.

**Comment by drescherflo** [comment]
After thinking about this feature again, I came to the point, that this feature is not needed.
What could be done is to let DefaultCard extend Ordered so we can easily compare them with each other. To search for wizards, we only need to call Card.isWizard.
Therefore, this feature will not get implemented as originally imagined.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
